### ISSUE TITLE
base.sh does not enable all services 

### ISSUE THREAD

**Issue by individual-it** [Bahmni/bahmni-vagrant#2]
the file https://github.com/Bahmni/bahmni-vagrant/blob/master/packer/scripts/base.sh does not enable the services bahmni-reports  & bahmni-erp-connect

Happy to make a PR if that is a bug

**Comment by bharatak** [comment]
@individual-it I agree it as a bug.  "yum install bahmni-erp-connect" is not included as part of install_bahmni step.  The bahmni-reports is included, but it is not started by default on vagrant up.  The reason is config_services() will not switch on the chkconfig for it.  You are free to submit the pull request and I will merge it.  Thanks for pointing it out.
